### ISSUE TITLE
is it SCA compliant?

### ISSUE THREAD

**Issue by jsappme** [braintree/braintree_express_example#44]
Is this demo SCA compliant? Does it follow 3DS2?

**Comment by hollabaq86** [comment]
👋  @jsappme this sample integration does not include 3DS at initial download(not everyone is in a regulatory environment that requires SCA). You can fork this sample repo and update as you need so that you have a [solution that includes 3DS](https://developers.braintreepayments.com/guides/3d-secure/client-side/javascript/v3#using-3ds).

We also have some sample [codepens](https://codepen.io/braintree) that demo 3DS client integrations with Hosted Fields or the Drop-In UI.

**Comment by jsappme** [comment]
Thank you @hollabaq86
